### ISSUE TITLE
Order by DESC clause works incorrectly for multiple fields

### ISSUE THREAD

**Issue by Seblink** [avrilfanomar/flexiblesearchbuilder#2]
There is a bug in the code when you try to order by multiple fields in a descending fashion. Only the last field is ordered descending, the other fields are ordered ascending.

The following code `xx.orderByDesc( field1, field2 ).build();` results in the generation of the following query: `ORDER BY { field1 },{ field2 } DESC`. This is interpreted as `ORDER BY { field1 } ASC ,{ field2 } DESC` by the SQL specification because `ASC` is the default ordering. 

One would expect that the generated code would be `ORDER BY { field1 } DESC, { field2 } DESC` based on the name of the method in the flexible search builder.

Ideally, the ordering would be revised so one can specificy multiple fields, and for every field separatly one can specify either ASC/DESC.

**Comment by avrilfanomar** [comment]
@Seblink thanks for reporting this! 
Probably the better syntax would be like `x.orderByDesc(field1).orderByAsc(field2)`.
I'll try to get my hands on it.
